server:
  name: grpc-cgi-proxy
  addr: 127.0.0.1
  port: 8081

monica:
  namespace: Production
  service_name: grpc-cgi-proxy
  token: a53d51e5-37fd-47ae-9867-e47cc8e9cec5

services:
  - service_name: go_wallet_manage_svr
    namespace: Production
    desc: 钱包服务
    methods:
      - cgi_path: /cgi-proxy/create_wallet
        method: GET
        desc: 创建钱包
        cmd: CreateWallet
        timeout: 1000
      - cgi_path: /cgi-proxy/import_wallet
        method: POST
        desc: 创建钱包
        cmd: ImportWallet
        timeout: 1000